// ISUFST Academic Calendar of Activities, AY 2026-2027.
// Month values are zero-indexed. Ranges appear on every included date.
const ACADEMIC_EVENTS = [
  // June 2026
  { year: 2026, month: 5, day: 1, endDay: 5, title: 'Enrollment for Summer Classes' },
  { year: 2026, month: 5, day: 1, endDay: 19, title: 'Review of Subject Loading and Assigned Faculty' },
  { year: 2026, month: 5, day: 5, title: 'Deadline: Undergraduate Grade Submission' },
  { year: 2026, month: 5, day: 8, title: 'First Day of Summer Classes' },
  { year: 2026, month: 5, day: 8, endDay: 20, title: 'First Trimester Enrollment' },
  { year: 2026, month: 5, day: 9, endDay: 11, title: 'Recognition Ceremonies' },
  { year: 2026, month: 5, day: 10, title: 'Midyear Assessment of IZN Partners' },
  { year: 2026, month: 5, day: 15, endDay: 17, title: 'Pre-enrollment for Waitlisted Applicants' },
  { year: 2026, month: 5, day: 16, title: 'Baccalaureate Mass' },
  { year: 2026, month: 5, day: 16, endDay: 18, title: 'Graduation Rehearsals' },
  { year: 2026, month: 5, day: 19, title: 'University-Wide Graduation Ceremony' },
  { year: 2026, month: 5, day: 22, endDay: 25, title: 'First-Year Enrollment' },
  { year: 2026, month: 5, day: 22, endDay: 26, title: 'Changing, Dropping and Comprehensive Exam Enrollment' },
  { year: 2026, month: 5, day: 27, title: 'SGS Orientation and Comprehensive Exam Enrollment' },
  { year: 2026, month: 5, day: 28, title: 'SGS Graduation and Regalia Hooding' },
  { year: 2026, month: 5, day: 29, title: 'Second-Year Enrollment' },

  // July 2026
  { year: 2026, month: 6, day: 1, endDay: 2, title: 'Second-Year Enrollment' },
  { year: 2026, month: 6, day: 3, title: 'USC Constitution and By-laws Revision' },
  { year: 2026, month: 6, day: 4, endDay: 19, title: 'First Trimester Subjects' },
  { year: 2026, month: 6, day: 6, endDay: 9, title: 'Third-Year Enrollment' },
  { year: 2026, month: 6, day: 7, endDay: 9, title: 'New Auditors Training' },
  { year: 2026, month: 6, day: 13, endDay: 16, title: 'Fourth-Year Enrollment' },
  { year: 2026, month: 6, day: 13, title: 'Homeroom Guidance Class' },
  { year: 2026, month: 6, day: 15, title: 'Mock Accreditation Phase 1 - Dingle' },
  { year: 2026, month: 6, day: 16, endDay: 17, title: 'SSC Strategic Planning' },
  { year: 2026, month: 6, day: 21, endDay: 23, title: 'CHED Program Evaluation Visit' },
  { year: 2026, month: 6, day: 23, title: 'First Federated USC Monthly Meeting' },
  { year: 2026, month: 6, day: 25, endDay: 26, title: 'Second Trimester Subject Sessions' },
  { year: 2026, month: 6, day: 27, title: 'First Day of First Semester Classes' },
  { year: 2026, month: 6, day: 27, title: 'Student Orientation and Campus Tour' },
  { year: 2026, month: 6, day: 27, endDay: 28, title: 'ISUFST Dingle Foundation Day' },
  { year: 2026, month: 6, day: 28, endDay: 31, title: 'Internal Quality Audit Phase 2' },
  { year: 2026, month: 6, day: 28, endDay: 29, title: 'In-Service Training and Organization Days' },
  { year: 2026, month: 6, day: 30, endDay: 31, title: 'SSC Strategic Planning' },
  { year: 2026, month: 6, day: 31, title: 'Deadline: IPCR Target Submission' },

  // August 2026
  { year: 2026, month: 7, day: 1, title: 'NSTP Orientation and Election of Officers' },
  { year: 2026, month: 7, day: 1, endDay: 9, title: 'Second First-Trimester Subject Sessions' },
  { year: 2026, month: 7, day: 3, title: 'Dumangas Student Orientation' },
  { year: 2026, month: 7, day: 3, endDay: 4, title: 'Mock Accreditation Phase 1' },
  { year: 2026, month: 7, day: 5, endDay: 6, title: 'Management Review' },
  { year: 2026, month: 7, day: 7, title: 'Second Federated USC Meeting and Pang abi-abi' },
  { year: 2026, month: 7, day: 8, title: 'University Clean-Up Drive' },
  { year: 2026, month: 7, day: 8, endDay: 16, title: 'Comprehensive Examination' },
  { year: 2026, month: 7, day: 10, endDay: 12, title: 'ASEAN Celebration' },
  { year: 2026, month: 7, day: 10, endDay: 12, title: 'Board Program Comprehensive Examination' },
  { year: 2026, month: 7, day: 14, title: 'Mock Accreditation Phase 2 - Dingle' },
  { year: 2026, month: 7, day: 20, title: 'Pag abi-abi kag Pagkilalahay' },
  { year: 2026, month: 7, day: 22, title: 'Admission Examination' },
  { year: 2026, month: 7, day: 27, title: 'Buwan ng Wika Celebration' },
  { year: 2026, month: 7, day: 27, endDay: 28, title: 'Neuropsychological Testing for Education Interns' },
  { year: 2026, month: 7, day: 28, title: 'Scholars and Grantees Orientation' },
  { year: 2026, month: 7, day: 28, title: 'Undergraduate Comprehensive Examination' },

  // September 2026
  { year: 2026, month: 8, day: 1, endDay: 10, title: 'Mock Accreditation Phase 2' },
  { year: 2026, month: 8, day: 3, title: 'Student General Assembly and Dialogue' },
  { year: 2026, month: 8, day: 4, title: 'Parents Consultative Dialogue' },
  { year: 2026, month: 8, day: 4, endDay: 25, title: 'Pre-Season Sports Activities' },
  { year: 2026, month: 8, day: 7, title: 'First Day of Prescribed University Uniform' },
  { year: 2026, month: 8, day: 7, endDay: 9, title: 'Accreditation Survey Visit - Dingle' },
  { year: 2026, month: 8, day: 7, endDay: 19, title: 'Second Trimester Enrollment' },
  { year: 2026, month: 8, day: 11, title: 'University-Wide Extension Symposium' },
  { year: 2026, month: 8, day: 12, title: 'USC Panugod and First Aid Seminar' },
  { year: 2026, month: 8, day: 14, endDay: 17, title: 'Fisheries Conservation Week' },
  { year: 2026, month: 8, day: 15, title: 'IAL Academic Year Orientation' },
  { year: 2026, month: 8, day: 18, title: 'Human Rights and Peace Education Forum' },
  { year: 2026, month: 8, day: 21, endDay: 23, title: 'Midterm Examination' },
  { year: 2026, month: 8, day: 21, endDay: 25, title: 'Changing, Dropping and Comprehensive Exam Enrollment' },
  { year: 2026, month: 8, day: 26, title: 'SGS New Student Orientation' },
  { year: 2026, month: 8, day: 28, title: 'Student Wellness Break' },
  { year: 2026, month: 8, day: 28, title: 'External ISO Surveillance Audit' },

  // October-December 2026
  { year: 2026, month: 9, day: 2, title: 'Student Wellness Break' },
  { year: 2026, month: 9, day: 2, title: 'Systemwide Extension In-House Review' },
  { year: 2026, month: 9, day: 5, title: 'Start of SCUAA Sports Practice' },
  { year: 2026, month: 9, day: 5, title: 'Start of University Entrance Exam Applications' },
  { year: 2026, month: 9, day: 5, endDay: 9, title: 'Accreditation Survey Visit' },
  { year: 2026, month: 9, day: 8, endDay: 22, title: 'Statistics Month Activities' },
  { year: 2026, month: 9, day: 9, title: 'Fourth Federated USC Monthly Meeting' },
  { year: 2026, month: 9, day: 11, title: 'Disaster Risk Reduction Training' },
  { year: 2026, month: 9, day: 14, title: 'Mental Health and Wellness Activity' },
  { year: 2026, month: 9, day: 16, title: 'Moral and Spiritual Recovery Program' },
  { year: 2026, month: 9, day: 17, title: 'Safe Campus and Gender Sensitivity Seminar' },
  { year: 2026, month: 9, day: 28, title: 'Start of First Semester Faculty Evaluation' },
  { year: 2026, month: 9, day: 30, title: 'Dagsa and Dagyaw' },
  { year: 2026, month: 10, day: 6, title: 'Fifth Federated USC Monthly Meeting' },
  { year: 2026, month: 10, day: 7, endDay: 15, title: 'Comprehensive Examination' },
  { year: 2026, month: 10, day: 12, title: 'Systemwide Completed Research Review' },
  { year: 2026, month: 10, day: 18, title: 'Health and Wellness Seminar' },
  { year: 2026, month: 10, day: 20, title: 'Last Day of First Semester Faculty Evaluation' },
  { year: 2026, month: 10, day: 21, title: 'Admission Examination' },
  { year: 2026, month: 10, day: 23, endDay: 25, title: 'Final Examination Week' },
  { year: 2026, month: 10, day: 23, endDay: 27, title: 'National Book Week Celebration' },
  { year: 2026, month: 10, day: 24, endDay: 26, title: 'Public Presentation of Research Outputs' },
  { year: 2026, month: 10, day: 26, endDay: 28, title: 'Peer Facilitators Training and Retreat' },
  { year: 2026, month: 11, day: 1, endDay: 4, title: 'University Week Celebration' },
  { year: 2026, month: 11, day: 1, endDay: 5, title: 'Tentative SCUAA 2026' },
  { year: 2026, month: 11, day: 3, title: 'Last Day for UEE Applications' },
  { year: 2026, month: 11, day: 7, title: 'End of First Semester' },
  { year: 2026, month: 11, day: 7, endDay: 19, title: 'Third Trimester Enrollment' },
  { year: 2026, month: 11, day: 8, endDay: 19, title: 'Semestral Break' },
  { year: 2026, month: 11, day: 11, title: 'Deadline: Grade Sheet Submission' },
  { year: 2026, month: 11, day: 14, title: 'Deadline: IPCR Submission' },
  { year: 2026, month: 11, day: 14, endDay: 29, title: 'Second Semester Enrollment' },
  { year: 2026, month: 11, day: 21, title: 'Start of Faculty Christmas Break' },

  // January-March 2027
  { year: 2027, month: 0, day: 4, title: 'First Day of Second Semester Classes' },
  { year: 2027, month: 0, day: 4, endDay: 8, title: 'Changing and Dropping of Subjects' },
  { year: 2027, month: 0, day: 9, title: 'NSTP First Day and Orientation' },
  { year: 2027, month: 0, day: 15, title: 'Sixth Federated USC Monthly Meeting' },
  { year: 2027, month: 0, day: 16, title: 'University Entrance Examination' },
  { year: 2027, month: 0, day: 17, endDay: 18, title: 'UEE Verification and Validation' },
  { year: 2027, month: 0, day: 21, title: 'Workplace and Internship Readiness Seminar' },
  { year: 2027, month: 0, day: 30, endDay: 31, title: 'Third Trimester Subject Sessions' },
  { year: 2027, month: 1, day: 4, title: 'Release of UEE Results' },
  { year: 2027, month: 1, day: 5, title: 'National Arts Month Celebration' },
  { year: 2027, month: 1, day: 6, endDay: 15, title: 'Aptitude Tests for Board Programs' },
  { year: 2027, month: 1, day: 6, endDay: 14, title: 'Comprehensive Examination' },
  { year: 2027, month: 1, day: 8, title: 'Interviews for Non-Board UEE Qualifiers' },
  { year: 2027, month: 1, day: 9, endDay: 17, title: 'Internal Audit Phase 1' },
  { year: 2027, month: 1, day: 10, title: 'National Anti-Hazing Prevention Week' },
  { year: 2027, month: 1, day: 12, title: 'Seventh Federated USC Monthly Meeting' },
  { year: 2027, month: 1, day: 17, title: 'Board Program Qualifier Interviews' },
  { year: 2027, month: 1, day: 20, title: 'Admission Examination' },
  { year: 2027, month: 2, day: 1, title: 'National Women’s Month Kick-Off' },
  { year: 2027, month: 2, day: 1, endDay: 3, title: 'Midterm Examination' },
  { year: 2027, month: 2, day: 3, endDay: 5, title: 'Student Electoral Board Applications' },
  { year: 2027, month: 2, day: 8, endDay: 20, title: 'Student Wellness Break and Summer Enrollment' },
  { year: 2027, month: 2, day: 10, endDay: 12, title: 'Kampsama - San Enrique Campus' },
  { year: 2027, month: 2, day: 15, endDay: 31, title: 'USC Filing of Candidacy' },
  { year: 2027, month: 2, day: 17, title: 'Release of First-Year Qualifiers AY 2027-2028' },
  { year: 2027, month: 2, day: 20, endDay: 27, title: 'Community Outreach Program - Pag-Ulikid' },
  { year: 2027, month: 2, day: 22, endDay: 23, title: 'Neuropsychological Testing for CFAS Interns' },
  { year: 2027, month: 2, day: 22, endDay: 26, title: 'Changing, Dropping and New Student Enrollment' },
  { year: 2027, month: 2, day: 24, title: 'Women’s Month Symposium' },
  { year: 2027, month: 2, day: 25, endDay: 28, title: 'Holy Week' },

  // April-July 2027
  { year: 2027, month: 3, day: 1, endDay: 7, title: 'USC Filing of Candidacy' },
  { year: 2027, month: 3, day: 1, endDay: 19, title: 'First-Year Pre-enrollment' },
  { year: 2027, month: 3, day: 2, title: 'Eighth Federated USC Monthly Meeting' },
  { year: 2027, month: 3, day: 3, title: 'New Student Orientation and Pagwaragwag' },
  { year: 2027, month: 3, day: 5, title: 'PRAISE Awards' },
  { year: 2027, month: 3, day: 5, endDay: 6, title: 'University Days Celebration' },
  { year: 2027, month: 3, day: 12, title: 'Announcement of Official USC Candidates' },
  { year: 2027, month: 3, day: 12, endDay: 21, title: 'Second Semester Faculty Evaluation' },
  { year: 2027, month: 3, day: 15, title: 'International Research Colloquium' },
  { year: 2027, month: 3, day: 16, title: 'Undergraduate Comprehensive Examination' },
  { year: 2027, month: 3, day: 16, endDay: 17, title: 'ISUFST Dingle Alumni Summer Gathering' },
  { year: 2027, month: 3, day: 19, endDay: 21, title: 'Final Examination for Graduating Students' },
  { year: 2027, month: 3, day: 21, title: 'USC Grand Rally' },
  { year: 2027, month: 3, day: 22, title: 'USC Election and Proclamation' },
  { year: 2027, month: 3, day: 23, title: 'Electoral Protest Filing and Hearing' },
  { year: 2027, month: 3, day: 26, title: 'USC Oath-Taking Program' },
  { year: 2027, month: 3, day: 29, title: 'Students Research Symposium' },
  { year: 2027, month: 4, day: 1, title: 'Dumangas Campus Alumni Homecoming' },
  { year: 2027, month: 4, day: 6, title: 'Deadline: Graduating Student Grades' },
  { year: 2027, month: 4, day: 8, endDay: 16, title: 'Comprehensive Examination' },
  { year: 2027, month: 4, day: 10, endDay: 12, title: 'Final Examination for Non-Graduating Students' },
  { year: 2027, month: 4, day: 13, title: 'Local Deliberation of Academic Awards' },
  { year: 2027, month: 4, day: 15, title: 'Main Campus Alumni Homecoming and Graduation Rites' },
  { year: 2027, month: 4, day: 16, title: 'Last Day of Faculty Service' },
  { year: 2027, month: 4, day: 17, title: 'Institutional Deliberation of Academic Awards' },
  { year: 2027, month: 4, day: 19, title: 'Pasidungog - University-Wide' },
  { year: 2027, month: 4, day: 20, title: 'Federated USC Election and Final Meeting' },
  { year: 2027, month: 4, day: 21, title: 'End of Second Semester' },
  { year: 2027, month: 4, day: 27, title: 'Deadline: Non-Graduating Grade Sheets' },
  { year: 2027, month: 4, day: 31, title: 'Start of Summer Enrollment' },
  { year: 2027, month: 5, day: 7, title: 'First Day of Summer Classes' },
  { year: 2027, month: 5, day: 8, endDay: 11, title: 'Recognition Ceremonies' },
  { year: 2027, month: 5, day: 11, title: 'ISUFST Job Fair' },
  { year: 2027, month: 5, day: 14, title: 'Baccalaureate Mass and Services' },
  { year: 2027, month: 5, day: 16, endDay: 17, title: 'Graduation Rehearsals' },
  { year: 2027, month: 5, day: 18, title: 'System-Wide Graduation' },
  { year: 2027, month: 5, day: 29, endDay: 30, title: 'Summer Midterm Examination' },
  { year: 2027, month: 6, day: 14, endDay: 30, title: 'Homeroom Guidance Class' },
  { year: 2027, month: 6, day: 19, endDay: 20, title: 'Summer Final Examination' },
  { year: 2027, month: 6, day: 19, endDay: 20, title: 'Accreditation Survey Visit - San Enrique' },
  { year: 2027, month: 6, day: 26, title: 'Mock Accreditation Phase 2 - San Enrique' }
].map(event => ({
  ...event,
  endDay: event.endDay || event.day,
  type: 'academic',
  group: 'academic',
  desc: 'ISUFST Academic Calendar of Activities, AY 2026-2027.'
}));
